### ISSUE TITLE
Breaks on Windows with Git Bash as default terminal

### ISSUE THREAD

**Issue by stefnotch** [CaptainUnbrauchbar/asp-language-support#10]
I'm on Windows and have VSCode configured to use the Git Bash as the default terminal.

To reproduce, make sure the following line is your `settings.json` and that you have the Git Bash installed
```
{
  ...
  "terminal.integrated.defaultProfile.windows": "Git Bash",
}
```

This ends up breaking the right click -> compute all answer sets.

**Comment by CaptainUnbrauchbar** [comment]
Fixed with next release 0.7.0 in a few minutes!
