### ISSUE TITLE
Settings do not refresh when changed

### ISSUE THREAD

**Issue by sjkillen** [CaptainUnbrauchbar/asp-language-support#3]
It would be nice to not have to restart vscode to change the config prop `selectOperatingSystem` (or if you decide to merge and #2, the `usePathClingo` option as well). Should be an easy fix after #1 and #2 are resolved.

**Comment by CaptainUnbrauchbar** [comment]
Just published your changes with a rudimentary settings fix! 
Thanks again for contributing :)
